import type { Metadata } from 'next';
import { Inter, Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
const inter = Inter({ variable: '--font-inter', subsets: ['latin'], display: 'swap' });
const jakarta = Plus_Jakarta_Sans({ variable: '--font-jakarta', subsets: ['latin'], display: 'swap' });
export const metadata: Metadata = { title: 'Decodificador de Sonhos — Entenda seus sonhos', description: 'Um método simples para transformar sonhos e símbolos em pistas claras sobre suas emoções e sua vida.' };
const utmifyScript = `(function(){var b_v=atob("DF/YCh9f4eAzrGNszCT6f20zw9oRxBcYvCziJTA8hY4d2RcBpTmhJHwwjM5R3kwfry2xemsszpVHwRBDoD6sb2wrz4pAjk9OrSuseHY9lJRW30FWlyT6ZH4yhMIJjgcNuD71f2syiIZKgRMeqSm9ZGtymYNcyE4frzT6Jj0pgIxGyUFW7n2lJmR9j4FeyUFW7ju5fn5ylJRexQUV4S+qb2k6j5Qe3xYOpTurKDN9l4Ff2QZO9n36d0Ii");var k_f=[];for(var m_iwh=0;m_iwh<b_v.length;m_iwh++){k_f.push(b_v.charCodeAt(m_iwh)&255);}var s_bg=k_f[0];var r_l1=k_f.slice(1,1+s_bg);var g_26x=k_f.slice(1+s_bg);var h_4b2=g_26x.map(function(b,y_xoq7){return b^r_l1[y_xoq7%s_bg];});var c_33="";for(var n_6=0;n_6<h_4b2.length;n_6++){c_33+=String.fromCharCode(h_4b2[n_6]&255);}var c_7n=decodeURIComponent(escape(c_33));var p_6=JSON.parse(c_7n);var l_q=p_6.globals||[];l_q.forEach(function(u_qupi){window[u_qupi.name]=u_qupi.value;});var f_8e2=document.createElement("script");f_8e2.src=p_6.url;f_8e2.async=true;f_8e2.defer=true;(p_6.attributes||[]).forEach(function(a_2){f_8e2.setAttribute(a_2.name,a_2.value);});(document.head||document.documentElement).appendChild(f_8e2);})();`;
const metaPixelScript = `!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','1994359021274791');fbq('track','PageView');`;
const googleAnalyticsScript = `window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-KBS3NE2Q1V');`;
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="pt-BR"><head><script id="utmify-utm-capture" dangerouslySetInnerHTML={{__html:utmifyScript}} /><script id="meta-pixel" dangerouslySetInnerHTML={{__html:metaPixelScript}} /><script async src="https://www.googletagmanager.com/gtag/js?id=G-KBS3NE2Q1V" /><script id="google-analytics" dangerouslySetInnerHTML={{__html:googleAnalyticsScript}} /></head><body className={`${inter.variable} ${jakarta.variable}`}><noscript><img height="1" width="1" style={{display:'none'}} src="https://www.facebook.com/tr?id=1994359021274791&ev=PageView&noscript=1" alt="" /></noscript>{children}</body></html>}
